import { useCallback, useEffect, useMemo, useState } from "preact/hooks";

import type NoteContext from "../../../components/note_context.js";
import { escapeHtml } from "../../../services/utils.js";
import type { HeadingContext } from "../../sidebar/TableOfContents.js";
import { type ContentBlock, getMessageText, type StoredMessage } from "./llm_chat_types.js";
import type { UseLlmChatReturn } from "./useLlmChat.js";

/** A single entry in the shared table-of-contents widget. */
type RawHeading = HeadingContext["headings"][number];

/** How far down the viewport (as a fraction of its height) the "you are here" line sits. */
const ACTIVATION_LINE_FRACTION = 0.3;

/**
 * Publishes a table of contents for an AI chat — one entry per user message — into the
 * note context, so the shared {@link TableOfContents} widget renders it exactly like the
 * text-note and PDF tables of contents. Also tracks which message is currently in view and
 * highlights the matching entry as the user scrolls.
 */
export function useChatToc(chat: UseLlmChatReturn, noteContext: NoteContext | undefined) {
    const { messages, scrollContainerRef } = chat;
    const [activeHeadingId, setActiveHeadingId] = useState<string | null>(null);

    const headings = useMemo(() => buildChatHeadings(messages), [messages]);

    const scrollToHeading = useCallback((heading: RawHeading) => {
        const el = findMessageElement(scrollContainerRef.current, heading.id);
        el?.scrollIntoView({ block: "start", behavior: "smooth" });
    }, [scrollContainerRef]);

    // Scroll-spy: recompute the active heading whenever the timeline scrolls or resizes.
    // Layout reads are batched into a single animation frame so a fast scroll can't queue
    // a backlog of reflows.
    useEffect(() => {
        const container = scrollContainerRef.current;
        if (!container) return;

        let rafId: number | null = null;
        const recompute = () => {
            rafId = null;
            const containerTop = container.getBoundingClientRect().top;
            const entries: HeadingOffset[] = [];
            for (const heading of headings) {
                const el = findMessageElement(container, heading.id);
                if (el) entries.push({ id: heading.id, top: el.getBoundingClientRect().top - containerTop });
            }
            const activationLine = container.clientHeight * ACTIVATION_LINE_FRACTION;
            setActiveHeadingId(pickActiveHeadingId(entries, activationLine));
        };
        const schedule = () => {
            if (rafId == null) rafId = requestAnimationFrame(recompute);
        };

        recompute();
        container.addEventListener("scroll", schedule, { passive: true });
        const resizeObserver = typeof ResizeObserver !== "undefined" ? new ResizeObserver(schedule) : null;
        resizeObserver?.observe(container);

        return () => {
            container.removeEventListener("scroll", schedule);
            resizeObserver?.disconnect();
            if (rafId != null) cancelAnimationFrame(rafId);
        };
    }, [headings, scrollContainerRef]);

    // Publish to the note context so the shared sidebar widget can consume it.
    useEffect(() => {
        noteContext?.setContextData("toc", { headings, scrollToHeading, activeHeadingId });
    }, [noteContext, headings, scrollToHeading, activeHeadingId]);
}

interface HeadingOffset {
    id: string;
    /** Distance (px) of the message's top edge below the scroll container's top edge. */
    top: number;
}

function findMessageElement(container: HTMLElement | null, messageId: string): HTMLElement | null {
    // Message IDs are generated by randomString() (alphanumeric), so they are safe to
    // interpolate straight into an attribute selector.
    return container?.querySelector<HTMLElement>(`[data-message-id="${messageId}"]`) ?? null;
}

/** Build one table-of-contents entry per user message, in order. */
export function buildChatHeadings(messages: StoredMessage[]): RawHeading[] {
    const headings: RawHeading[] = [];
    for (const message of messages) {
        if (message.role !== "user") continue;
        const preview = truncateForToc(getMessagePreviewText(message.content));
        // The shared widget renders `text` as HTML (via RawHtml), so escape the plain
        // message text so it renders literally and can't inject markup.
        headings.push({ id: message.id, level: 1, text: escapeHtml(preview) });
    }
    return headings;
}

/** Pick the entry whose section the reader is currently in: the last one scrolled past the activation line. */
export function pickActiveHeadingId(entries: HeadingOffset[], activationLine: number): string | null {
    if (entries.length === 0) return null;
    // Default to the first entry so that when nothing has been scrolled past yet
    // (all messages sit below the line) the top entry is highlighted.
    let active = entries[0].id;
    for (const entry of entries) {
        if (entry.top <= activationLine) active = entry.id;
    }
    return active;
}

/**
 * The text used to preview a user message in the table of contents. Falls back to an
 * attachment's title for messages that carry only an image or file and no prose.
 */
function getMessagePreviewText(content: string | ContentBlock[]): string {
    const text = getMessageText(content);
    if (text.trim()) return text;
    if (Array.isArray(content)) {
        for (const block of content) {
            if ((block.type === "image" || block.type === "file" || block.type === "text_file") && block.title) {
                return block.title;
            }
        }
    }
    return "";
}

const ELLIPSIS = "…";

export interface TruncateOptions {
    /** Maximum number of words to keep. */
    maxWords?: number;
    /** Hard cap on the character (grapheme) count of the whole result, ellipsis included. */
    maxChars?: number;
}

/**
 * Produce a short, single-line preview of a chat message for the table of contents.
 *
 * Collapses whitespace, keeps at most `maxWords` words, then hard-caps the result at
 * `maxChars` characters as a defence against a single very long / malformed "word".
 * Word and character boundaries are found with `Intl.Segmenter`, so it behaves correctly
 * across cultures — scripts without spaces (e.g. Chinese, Japanese), combining marks, and
 * multi-code-point emoji — rather than naively splitting on spaces or UTF-16 units.
 */
export function truncateForToc(text: string, { maxWords = 7, maxChars = 128 }: TruncateOptions = {}): string {
    // Collapse every run of whitespace (including newlines) into a single space for a one-line label.
    const normalized = text.replace(/\s+/g, " ").trim();
    if (!normalized) return "";

    const word = truncateToWords(normalized, maxWords);
    // Grapheme-cap the (possibly word-truncated) text. When an ellipsis will be appended,
    // leave room for it so the final string never exceeds `maxChars`.
    let truncated = word.truncated;
    const initialCap = truncateToGraphemes(word.text, maxChars);
    truncated = truncated || initialCap.truncated;
    let result = truncated ? truncateToGraphemes(initialCap.text, maxChars - 1).text : initialCap.text;

    result = result.trimEnd();
    return truncated ? result + ELLIPSIS : result;
}

interface TruncationResult {
    text: string;
    truncated: boolean;
}

function truncateToWords(text: string, maxWords: number): TruncationResult {
    if (maxWords <= 0) return { text: "", truncated: text.length > 0 };

    const segmenter = getSegmenter("word");
    if (!segmenter) {
        // Fallback for environments without Intl.Segmenter: naive whitespace split.
        const parts = text.split(" ");
        if (parts.length <= maxWords) return { text, truncated: false };
        return { text: parts.slice(0, maxWords).join(" "), truncated: true };
    }

    let wordCount = 0;
    let cutIndex = text.length;
    for (const { segment, index, isWordLike } of segmenter.segment(text)) {
        if (!isWordLike) continue;
        wordCount++;
        if (wordCount === maxWords) {
            // Remember where the last kept word ends, dropping any trailing punctuation/space.
            cutIndex = index + segment.length;
        } else if (wordCount > maxWords) {
            return { text: text.slice(0, cutIndex), truncated: true };
        }
    }
    return { text, truncated: false };
}

function truncateToGraphemes(text: string, maxGraphemes: number): TruncationResult {
    if (maxGraphemes <= 0) return { text: "", truncated: text.length > 0 };

    const segmenter = getSegmenter("grapheme");
    if (!segmenter) {
        // Fallback: count code points so surrogate pairs are at least kept intact.
        const codePoints = [...text];
        if (codePoints.length <= maxGraphemes) return { text, truncated: false };
        return { text: codePoints.slice(0, maxGraphemes).join(""), truncated: true };
    }

    let count = 0;
    for (const { index } of segmenter.segment(text)) {
        if (count === maxGraphemes) return { text: text.slice(0, index), truncated: true };
        count++;
    }
    return { text, truncated: false };
}

let wordSegmenter: Intl.Segmenter | null | undefined;
let graphemeSegmenter: Intl.Segmenter | null | undefined;

function getSegmenter(granularity: "word" | "grapheme"): Intl.Segmenter | null {
    if (typeof Intl === "undefined" || typeof Intl.Segmenter === "undefined") return null;
    if (granularity === "word") {
        wordSegmenter ??= new Intl.Segmenter(undefined, { granularity: "word" });
        return wordSegmenter;
    }
    graphemeSegmenter ??= new Intl.Segmenter(undefined, { granularity: "grapheme" });
    return graphemeSegmenter;
}
